COURSE_ACTS(COURSE_BOB, _(" 1 KXANG-ANGÄ KXUTSENG"),
       _("APXA KXANG-ANG SÌN RAM")        , _("SÄWÄSUL A TUL WÄ LANTELAK AWIN"), _("TEM NE SPONO A TOK TAWTI"),
       _("RUN VOLA FNGAPIT ATUN")         , _("MARIO TSWAYON FA MESYAL")       , _("UO RAWNG ZA'ÄFRÌPÄ"))

COURSE_ACTS(COURSE_WF, _(" 2 WOMPÄ TXURTSENG"),
       _("WOMPÄ TSKXETI RIPX")            , _("SÌN TXURTSENGÄ FÄPA")           , _("TSWAYON NEMFA TAW"),
       _("TUNA FNGAP LUSÌNGA SPONOSÌN")   , _("ZUP SÌN SPONO A NGA' PXAWPAT")  , _("TEM FTE KXEMYOÄ HAPXÌT 'IVAKU"))

COURSE_ACTS(COURSE_JRB, _(" 3 WIPA WION A WAPX"),
       _("TSYEYM MÌ URAN A WOLAPX")       , _("CAN THE EEL COME OUT TO PLAY?") , _("TSYEYM SLÄRÄ TXAMPAYÄ"),
       _("TUNA FNGAP SÌN URAN A FWUM")    , _("TEM NE SWEK LETSKXE")           , _("WÄ FAYFYA"))

COURSE_ACTS(COURSE_CCM, _(" 4 WURA RAM AWUR"),
       _("TSKXEPAYSÌN FWI")               , _("LI'L PENGUIN LOST")             , _("BIG PENGUIN RACE"),
       _("FWI NÌWEW FPI VOLA FNGAP ATUN") , _("HERWÌTUL RE'OT HOLAN")          , _("KINAMFA PXEK KXEMYOT"))

COURSE_ACTS(COURSE_BBH, _(" 5 APXA 'ASAPÄ KELKU"),
       _("TARON FRATIREAT")               , _("RIDE BIG BOO'S MERRY-GO-ROUND") , _("UKÄ FUKÄ INGYENTSIM"),
       _("VOLA FNGAPÌL ATUN PESENGTI?")   , _("BIG BOO'S BALCONY")             , _("MORU AWAWNAN TÌNG NARI"))

COURSE_ACTS(COURSE_HMC, _(" 6 SLÄR A SKIEN LU FTÄR"),
       _("SWIRÄ SLELE MÌ SLÄR")           , _("FÄKÄ FPI SUNA FNGAP AVOL")      , _("MARIO LEFNGAP TSUN TIVUL!"),
       _("ÌLÄ EYAWRFYA YAVÄ'MÌ")          , _("HUM LAHEA FYA'OFA LEYE'KRR")    , _("SKXERI A'USRRKO NARI SI"))

COURSE_ACTS(COURSE_LLL, _(" 7 VRRTEPÄ TXEP A SYEP"),
       _("NEKX APXA ÄZANTUTI")            , _("ÄZAN SI PXEÄZANTUR")            , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _("10 UKXOA ATXKXE NENIYÄ"),
       _("IN THE TALONS OF THE BIG BIRD") , _("SHINING ATOP THE PYRAMID")      , _("INSIDE THE ANCIENT PYRAMID"),
       _("STAND TALL ON THE FOUR PILLARS"), _("FREE FLYING FOR 8 RED COINS")   , _("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _("11 URANÄ UTURU"),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("12 HERWÌTUÄ TXANLOKXE"),
       _("APXA RE'O HERWÌTUÄ")            , _("WRRKÄ WURA ÄZANTUHU")           , _("IN THE DEEP FREEZE"),
       _("WHIRL FROM THE FREEZING POND")  , _("SHELL SHREDDIN' FOR RED COINS") , _("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("13 UKXOA KIFKEY AMEI"),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("14 TSAWLA RAM ATSAWL"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("15 APXA SPONO AHÌ'I"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("16 TÌK TXEW LOK"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("17 KATIRÄ SALEWFYA"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   PAWSER MÌ VAWMA KIFKEY"))
SECRET_STAR(COURSE_BITFS, _("   PAWSER MÌ TXAMPAY APUSALON"))
SECRET_STAR(COURSE_BITS, _("   PAWSER MÌ SAW"))
SECRET_STAR(COURSE_PSS, _("   PITSYÄ WAWNANA FYA'O A FWI"))
SECRET_STAR(COURSE_COTMC, _("   SLÄR HAWRE'Ä LEFNGAP"))
SECRET_STAR(COURSE_TOTWC, _("   ASIP HAWRE'Ä A TSWAYON"))
SECRET_STAR(COURSE_VCUTM, _("   HAWRE' A 'ÌP ROFA SE'AYL"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO KATIRIO TSWAYON"))
SECRET_STAR(COURSE_SA, _("   WAWNANA MO FAYOANGÄ"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   AYSANHÌ AWAWNAN"))

EXTRA_TEXT(0, _("'AWA PUM SANHÌYÄ AWAWNAN!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
