COURSE_ACTS(COURSE_BOB, _(" 1 KXANG-ANGÄ KXUTSENG"),
       _("APXA KXANG-ANG SÌN RAM")        , _("SÄWÄSUL A TUL WÄ LANTELAK AWIN"), _("TEM NE SPONO A TOK TAWTI"),
       _("RUN VOLA FNGAPIT ATUN")         , _("MARIO TSWAYON FA MESYAL")       , _("UO RAWNG ZA'ÄFRÌPÄ"))

COURSE_ACTS(COURSE_WF, _(" 2 WOMPÄ TXURTSENG"),
       _("WOMPÄ TSKXETI RIPX")            , _("SÌN TXURTSENGÄ FÄPA")           , _("TSWAYON NEMFA TAW"),
       _("TUNA FNGAP LUSÌNGA SPONOSÌN")   , _("ZUP SÌN SPONO A NGA' PXAWPAT")  , _("TEM FTE KXEMYOÄ HAPXÌT 'IVAKU"))

COURSE_ACTS(COURSE_JRB, _(" 3 WIPA WION A WAPX"),
       _("TSYEYM MÌ URAN A WOLAPX")       , _("WRRKIVÄ MA VAKX APXA")          , _("TSYEYM SLÄRÄ TXAMPAYÄ"),
       _("TUNA FNGAP SÌN URAN A FWUM")    , _("TEM NE SWEK LETSKXE")           , _("WÄ FAYFYA"))

COURSE_ACTS(COURSE_CCM, _(" 4 WURA RAM AWUR"),
       _("TSKXEPAYSÌN FWI")               , _("YAYOTSYÌP LU LOM")              , _("FWI WÄ YAYO APXA"),
       _("FWI NÌWEW FPI VOLA FNGAP ATUN") , _("HERWÌTUL RE'OT HOLAN")          , _("KINAMFA PXEK KXEMYOT"))

COURSE_ACTS(COURSE_BBH, _(" 5 APXA 'ASAPÄ KELKU"),
       _("TARON FRATIREAT")               , _("APXA 'ASAPÄ 'O'A MO A MÌN")     , _("UKÄ FUKÄ INGYENTSIM"),
       _("VOLA FNGAPÌL ATUN PESENGTI?")   , _("FÄPA KELKUÄ APXA 'ASAPÄ")       , _("MORU AWAWNAN TÌNG NARI"))

COURSE_ACTS(COURSE_HMC, _(" 6 SLÄR A SKIEN LU FTÄR"),
       _("SWIRÄ SLELE MÌ SLÄR")           , _("FÄKÄ FPI SUNA FNGAP AVOL")      , _("MARIO LEFNGAP TSUN TIVUL!"),
       _("ÌLÄ EYAWRFYA YAVÄ'MÌ")          , _("HUM LAHEA FYA'OFA LEYE'KRR")    , _("SKXERI A'USRRKO NARI SI"))

COURSE_ACTS(COURSE_LLL, _(" 7 VRRTEPÄ TXEP A SYEP"),
       _("NEKX APXA ÄZANTUTI")            , _("ÄZAN SI PXEÄZANTUR")            , _("VOHINA HAPXÌ SÌ VOLA FNGAP"),
       _("''EYKRRKO TANGEKIT FA FWA TUL") , _("TXEPRAMÄ TXE'LANMÌ")            , _("YO A RIKX FYAWÌNTXU MÌ TEPRAM"))

COURSE_ACTS(COURSE_SSL, _("10 UKXOA ATXKXE NENIYÄ"),
       _("MÌ SAWLA YAYOÄ SIN")            , _("NER TÌTXULAYÄ FÄPAMÌ")          , _("MÌ SÌTXULA ATXANLAL"),
       _("KLLKXEM SÌN ASIP ATSÌNG")       , _("TSWAYON FPI VOLA FNGAP ATUN")   , _("TÌTXULAYÄ INGYENTSIM"))

COURSE_ACTS(COURSE_DDD, _("11 URANÄ UTURU"),
       _("FÄKÄ SÌN URAN PAWSERÄ")         , _("TSYEYMÄ AYSÄHENA MÌ SWESYA")    , _("SPÄ SWEKFTU FPI FNGAP ATUN"),
       _("WÄ FAYFYA")                     , _("SLOAPEKÄ STXELI")               , _("STARSÌM MEHAWRE'TI..."))

COURSE_ACTS(COURSE_SL, _("12 HERWÌTUÄ TXANLOKXE"),
       _("APXA RE'O HERWÌTUÄ")            , _("WRRKÄ WURA ÄZANTUHU")           , _("NEMFA ZUM A TA TSKXEPAY"),
       _("MÌN IO LEYRA 'ORATSYÌP")        , _("TUNA FNGAPFPI MAKTO LAKTI")     , _("TSLIKX NEMFA KELKUTSYÌP"))

COURSE_ACTS(COURSE_WDW, _("13 UKXOA KIFKEY AMEI"),
       _("NONG AYSWIZAWTI AEAN")          , _("FÄKÄ NE FÄPA")                  , _("AYU AWAWNAN NÌRENG NÌKXAYLSÌ"),
       _("YO A KLLKÄ FÄKÄ--WIN SÄPI KO!") , _("TUNA FNGAP MÌ SRAY")            , _("TUL NÌWIN KXAMLÄ TSRAY!"))

COURSE_ACTS(COURSE_TTM, _("14 TSAWLA RAM ATSAWL"),
       _("TSYÌL TSAWLA RAMIT")            , _("SYAKSYUKÄ MOÄ INGYENTSIM")      , _("KXAYLA AYSPXAM SÌ TUNA FNGAP"),
       _("INGYENGA'A PA'O RAMÄ")          , _("TÌNG NARI FTU SEMKÄ")           , _("TSWAYON NE SPXAM LE'AWTU"))

COURSE_ACTS(COURSE_THI, _("15 APXA SPONO AHÌ'I"),
       _("TSAWN YOMVEY'EWLLTI")           , _("RO FÄPA SPONOÄ APXA")           , _("TUL NÌMUN WÄ LANTELAK AWIN"),
       _("WAWNANA 'UTSYÌP AMRR")          , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("16 TÌK TXEW LOK"),
       _("NEMFA MO SÌN 'RRKO A YO")       , _("THE PIT AND THE PENDULUMS")     , _("SWIZAWSÌN AMUSÌN"),
       _("SPÄ SÌN SRU'YU")                , _("SPÄ NÌKMAR SÌN PXEZUM A RIKX")  , _("TÌFTANG SI KRRTI TUNA FNGAPFPI"))

COURSE_ACTS(COURSE_RR, _("17 KATIRÄ SALEWFYA"),
       _("URAN A KATIRIT EMKÄ")           , _("APXA KELKU MÌ SAW")             , _("STARSÌM FNGAPIT KEMYORO"),
       _("HUFWETSYÌPIT 'EFU")             , _("LEYKATEM AYONTI AHIYÌK")        , _("TSENGO NUÄ HATIR"))

SECRET_STAR(COURSE_BITDW, _("   PAWSER MÌ VAWMA KIFKEY"))
SECRET_STAR(COURSE_BITFS, _("   PAWSER MÌ TXAMPAY APUSALON"))
SECRET_STAR(COURSE_BITS, _("   PAWSER MÌ SAW"))
SECRET_STAR(COURSE_PSS, _("   PITSYÄ WAWNANA FYA'O A FWI"))
SECRET_STAR(COURSE_COTMC, _("   SLÄR HAWRE'Ä LEFNGAP"))
SECRET_STAR(COURSE_TOTWC, _("   ASIP HAWRE'Ä A TSWAYON"))
SECRET_STAR(COURSE_VCUTM, _("   HAWRE' A 'ÌP ROFA SE'AYL"))
SECRET_STAR(COURSE_WMOTR, _("   MARIO KATIRIO TSWAYON"))
SECRET_STAR(COURSE_SA, _("   WAWNANA MO FAYOANGÄ"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   AYSANHÌ AWAWNAN"))

EXTRA_TEXT(0, _("'AWA PUM SANHÌYÄ AWAWNAN!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
